[package]
name = "frog_gui"
version = "0.2.0"
edition = "2024"

[dependencies]
frogcore = {path="../frogcore"}
serde_inspector = {path="../serde_inspector"}
serde_json = "1.0.138"
egui = "0.34"
egui_extras = "0.34"
macroquad = "0.4.14"
egui-macroquad = {path="../egui-macroquad"}
egui_dock = "0.19"
slotmap = "1.1.1"
rfd = "0.17.2"
